language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10

os:
  - linux
  - osx

install:
  - make packages

matrix:
  # make status as green if all tests passed (except for allow_failures)
  fast_finish: true

  script:
  - go test
